name: publish

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: docker hub login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: prepare buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: build python
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/python:3
            ${{ secrets.DOCKERHUB_USERNAME }}/python:latest

      - name: image identifiers
        run: echo ${{ steps.docker_build.outputs.digest }}
